{
 "title": "Mesh and Envoy Details",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "osm_controller_instance",
    "label": "OSM Controller instance",
    "query": "label_values(osm_proxy_connect_count, source_pod_name)"
   },
   {
    "name": "osm_injector_instance",
    "label": "OSM Injector instance",
    "query": "label_values(osm_injector_injector_sidecar_count, source_pod_name)"
   },
   {
    "name": "xds_path",
    "label": "xDS Path",
    "query": "label_values(osm_proxy_config_update_time_bucket, resource_type)"
   },
   {
    "name": "osm_error_code",
    "label": "OSM Error Code",
    "query": "label_values(osm_error_err_code_count, err_code)"
   }
  ]
 },
 "panels": [
  { "title": "Mesh Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitored Namespaces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(osm_resource_namespace_count{source_pod_name=~\"$osm_controller_instance\"}) by (source_pod_name)",
     "legendFormat": "{{source_pod_name}}"
    }
   ]
  },
  {
   "title": "Services in the Mesh",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(osm_resource_service_count{source_pod_name=~\"$osm_controller_instance\"}) by (source_pod_name)",
     "legendFormat": "{{source_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(osm_resource_pod_count{source_pod_name=~\"$osm_controller_instance\"}) by (source_pod_name)",
     "legendFormat": "{{source_pod_name}}"
    }
   ]
  },
  {
   "title": "Connected Proxies",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "osm_proxy_connect_count{source_pod_name=~\"$osm_controller_instance\"}",
     "legendFormat": "Connected proxies"
    }
   ]
  },
  {
   "title": "Avg Envoy Update Time (s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4.5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg_over_time(osm_proxy_config_update_time_sum{resource_type=\"$xds_path\", source_pod_name=~\"$osm_controller_instance\"}[1y:1s])",
     "legendFormat": "{{source_pod_name}}"
    }
   ]
  },
  {
   "title": "Max Envoy Update Time (s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4.5, "x": 4.5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max_over_time(osm_proxy_config_update_time_sum{resource_type=\"$xds_path\", source_pod_name=~\"$osm_controller_instance\"}[1y:1s])",
     "legendFormat": "{{source_pod_name}}"
    }
   ]
  },
  {
   "title": "Control plane resource consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "CPU%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"osm-system\", container!~\"POD\", container!~\"\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RSS Memory footprint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"osm-system\", container!=\"\", container!=\"POD\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "OSM Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Sidecar injector timings (sec)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "idelta(osm_injector_injector_rq_time_bucket{source_pod_name=~\"$osm_injector_instance\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Certificate Issue timings (sec)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 21 },
   "targets": [
    {
     "expr": "sum(idelta(osm_cert_issued_time_bucket{source_pod_name=~\"$osm_injector_instance\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "xDS Path histogram",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(idelta(osm_proxy_config_update_time_bucket{resource_type=\"$xds_path\", source_pod_name=~\"$osm_controller_instance\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Injector Webhooks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "idelta(osm_injector_injector_rq_time_count{success=\"true\", source_pod_name=~\"$osm_injector_instance\"}[1m])\n",
     "legendFormat": "Success"
    },
    {
     "expr": "idelta(osm_injector_injector_rq_time_count{success=\"false\", source_pod_name=~\"$osm_injector_instance\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "xDS Updates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "idelta(osm_proxy_config_update_time_count{success=\"true\", resource_type=~\"$xds_path\", source_pod_name=~\"$osm_controller_instance\"}[1m])\n",
     "legendFormat": "{{resource_type}}-{{source_pod_name}}-Success"
    },
    {
     "expr": "idelta(osm_proxy_config_update_time_count{success=\"false\", resource_type=~\"$xds_path\", source_pod_name=~\"$osm_controller_instance\"}[1m])",
     "legendFormat": "{{resource_type}}-{{source_pod_name}}-Failure"
    }
   ]
  },
  { "title": "OSM Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Rate of Increase of OSM Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(osm_error_err_code_count{source_pod_name=~\"$osm_controller_instance\",err_code=~\"$osm_error_code\"}[1m])",
     "legendFormat": "{{source_pod_name}}"
    },
    {
     "expr": "rate(osm_error_err_code_count{source_pod_name=~\"$osm_injector_instance\",err_code=~\"$osm_error_code\"}[1m])",
     "legendFormat": "{{source_pod_name}}"
    }
   ]
  },
  {
   "title": "OSM Controller Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(osm_error_err_code_count{source_pod_name=~\"$osm_controller_instance\",err_code=~\"$osm_error_code\"}[1m])\n",
     "legendFormat": "{{err_code}}, {{source_pod_name}}"
    }
   ]
  },
  {
   "title": "OSM Injector Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(osm_error_err_code_count{source_pod_name=~\"$osm_injector_instance\",err_code=~\"$osm_error_code\"}[1m])",
     "legendFormat": "{{err_code}}, {{source_pod_name}}"
    }
   ]
  }
 ]
}