apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"bookstore","namespace":"bookstore"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"bookstore"}},"template":{"metadata":{"labels":{"app":"bookstore"}},"spec":{"containers":[{"args":["--port","14001"],"command":["/bookstore"],"env":[{"name":"BOOKWAREHOUSE_NAMESPACE","value":"bookwarehouse"},{"name":"IDENTITY","value":"bookstore-v1"}],"image":"openservicemesh/bookstore:v1.0.0-rc.3","imagePullPolicy":"Always","name":"bookstore","ports":[{"containerPort":14001,"name":"web"}]}],"nodeSelector":{"kubernetes.io/arch":"amd64","kubernetes.io/os":"linux"},"serviceAccountName":"bookstore"}}}}
  creationTimestamp: "2022-01-13T16:24:09Z"
  generation: 1
  name: bookstore
  namespace: bookstore
  resourceVersion: "216612"
  uid: e6b81f28-ec3c-4d2b-8638-2e4bf84da9ec
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bookstore
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bookstore
    spec:
      containers:
      - args:
        - --port
        - "14001"
        command:
        - /bookstore
        env:
        - name: BOOKWAREHOUSE_NAMESPACE
          value: bookwarehouse
        - name: IDENTITY
          value: bookstore-v1
        image: openservicemesh/bookstore:v1.0.0-rc.3
        imagePullPolicy: Always
        name: bookstore
        ports:
        - containerPort: 14001
          name: web
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookstore
      serviceAccountName: bookstore
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-13T16:24:16Z"
    lastUpdateTime: "2022-01-13T16:24:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-13T16:24:09Z"
    lastUpdateTime: "2022-01-13T16:24:16Z"
    message: ReplicaSet "bookstore-7776774756" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
